### ISSUE TITLE
License

### ISSUE THREAD

**Issue by slhck** [gitlab-container-registry-cleaner/gitlab-container-registry-cleaner#1]
Thanks for this useful repo! Could you please add a license to it?

**Comment by PierreBeucher** [comment]
Hi there, thanks ! Certainly, will do

**Comment by PierreBeucher** [comment]
Done :) Hesitated between Apache and GPLv3, but I think Apache is more suitable for this project.

**Comment by slhck** [comment]
Thank you!

**Comment by PierreBeucher** [comment]
My pleasure ! As I provided this software for free, may I inquire what usage you intend to have for it ?

**Comment by slhck** [comment]
I have a Gitlab instance that has accumulated a lot of images I need to clean up.

I have some updates that I'll push to a fork, including some more GUI features and options for retaining tags. I'll let you know in case you want to merge those back to your repo!

**Comment by PierreBeucher** [comment]
Great, thanks !

**Comment by slhck** [comment]
I ended up making more changes, so it's probably hard to get a clean diff (since I also applied automatic formatting).

The repo is here: https://github.com/slhck/gitlab-container-registry-cleaner

Let me know your thoughts about whether you want to merge the fork completely, or keep your own code base separate. I am planning to add more features and am considering publishing to `npm`, but I didn't want to take away your project's name, so I can also rename mine to something different if you like.

**Comment by PierreBeucher** [comment]
I'll happily accept PR and make you co-maintainer of this project to keep both of our work together :)

**Comment by slhck** [comment]
Thanks for the suggestion! I'll happily accept — but do you think we should maybe create a new GitHub organization to sort of make it independent?

**Comment by PierreBeucher** [comment]
Seems fair yes, I'll do that. As I'm someone very original, how about `gitlab-container-registry-cleaner ` as org name ? Repo would be `gitlab-container-registry-cleaner/gitlab-container-registry-cleaner `

**Comment by slhck** [comment]
That sounds exciting 😅 Yes, let's do that!
