### ISSUE TITLE
Add possibility to use -o option with given project

### ISSUE THREAD

**Issue by zesaver** [gitlab-container-registry-cleaner/gitlab-container-registry-cleaner#5]
Hello, I need to clean up one project that is holding multiple repositories. I want to be able to run the cleaner with the following options: `./gitlab-container-registry-cleaner list project ID -o /tmp/repositories.json`.

Current behavior:

```
$ ./gitlab-container-registry-cleaner list project 1 -o /tmp/repositories.json
error: unknown option '-o
```

Expected behavior:

The same as when running `./gitlab-container-registry-cleaner list all -o /tmp/repositories.json`, but for one project (or group, possibly) only.

End notes:

Thank you for the great tool, saving time and nerves while maintaining a self-hosted GitLab.

**Comment by PierreBeucher** [comment]
Hi there, thanks for your feedback happy to see this project in use :)

Can you use something like this maybe:

```
./gitlab-container-registry-cleaner list project 1 > /tmp/repositories.json
```

Which is equivalent without requiring a custom flag

**Comment by slhck** [comment]
This is possible now in v0.0.6!

**Comment by PierreBeucher** [comment]
Faster than lightning :zap: well done !
